"""create notification table

Revision ID: 1fa05e15d66e
Revises: ef56d38fbb59
Create Date: 2026-04-03 18:18:20.040820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa05e15d66e'
down_revision: Union[str, Sequence[str], None] = 'ef56d38fbb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='接收用户ID'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('type', sa.SmallInteger(), nullable=False, comment='类型：1-审批结果，2-预约失效，3-系统通知'),
    sa.Column('related_id', sa.Integer(), nullable=True, comment='关联ID'),
    sa.Column('is_read', sa.SmallInteger(), nullable=False, comment='是否已读：0-未读，1-已读'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
