"""add attachment to notification

Revision ID: 7af038960a21
Revises: 90e3a49ab18b
Create Date: 2026-04-04 02:57:50.436888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7af038960a21'
down_revision: Union[str, Sequence[str], None] = '90e3a49ab18b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('attachment', sa.Text(), nullable=True, comment='附件JSON数据（智能推荐等）'))
    op.alter_column('notification', 'type',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='类型：1-审批结果，2-预约失效，3-系统通知，4-智能推荐',
               existing_comment='类型：1-审批结果，2-预约失效，3-系统通知',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'type',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='类型：1-审批结果，2-预约失效，3-系统通知',
               existing_comment='类型：1-审批结果，2-预约失效，3-系统通知，4-智能推荐',
               existing_nullable=False)
    op.drop_column('notification', 'attachment')
    # ### end Alembic commands ###
