"""create agent_log table

Revision ID: 90e3a49ab18b
Revises: 1fa05e15d66e
Create Date: 2026-04-04 02:55:31.141865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e3a49ab18b'
down_revision: Union[str, Sequence[str], None] = '1fa05e15d66e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('input_message', sa.String(length=500), nullable=False, comment='用户输入摘要'),
    sa.Column('context_file', sa.String(length=100), nullable=False, comment='上下文文件路径'),
    sa.Column('is_completed', sa.SmallInteger(), nullable=False, comment='是否完成：0-进行中，1-已完成，2-已放弃'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_log')
    # ### end Alembic commands ###
