"""initial migration

Revision ID: b3d166389bb2
Revises: 
Create Date: 2026-03-23 00:31:09.188989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d166389bb2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='标签ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='标签名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('role', sa.SmallInteger(), server_default='2', nullable=False, comment='角色（0-超级管理员 1-管理员 2-实验员）'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='电话号码'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('is_active', sa.SmallInteger(), server_default='0', nullable=False, comment='是否启用，0-启用，1-封禁，2-注销'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_table('lab',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='实验室ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='名称'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='地址'),
    sa.Column('capacity', sa.Integer(), nullable=True, comment='容纳人数（NULL-未设置）'),
    sa.Column('status', sa.SmallInteger(), server_default='0', nullable=False, comment='状态(0-正常 1-维护 2-停用)'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='标签编号'),
    sa.Column('keyword', sa.String(length=255), nullable=True, comment='关键词，用于大模型检索'),
    sa.Column('description', sa.Text(), nullable=True, comment='实验室说明'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_tag_id'), 'lab', ['tag_id'], unique=False)
    op.create_table('tag_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='日志ID'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='标签ID'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作人ID'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='操作类型(create/update/delete)'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='标签名'),
    sa.Column('description', sa.String(length=255), nullable=False, comment='描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='操作时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_log_created_at'), 'tag_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_tag_log_operator_id'), 'tag_log', ['operator_id'], unique=False)
    op.create_index(op.f('ix_tag_log_tag_id'), 'tag_log', ['tag_id'], unique=False)
    op.create_table('tag_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='标签ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'user_id', name='tag_id_user_id_unique')
    )
    op.create_table('tag_user_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='日志ID'),
    sa.Column('tag_user_id', sa.Integer(), nullable=False, comment='被操作的记录ID'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='标签ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作人ID'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='操作类型(create/update/delete)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='操作时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_user_log_created_at'), 'tag_user_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_tag_user_log_operator_id'), 'tag_user_log', ['operator_id'], unique=False)
    op.create_index(op.f('ix_tag_user_log_tag_id'), 'tag_user_log', ['tag_id'], unique=False)
    op.create_index(op.f('ix_tag_user_log_tag_user_id'), 'tag_user_log', ['tag_user_id'], unique=False)
    op.create_index(op.f('ix_tag_user_log_user_id'), 'tag_user_log', ['user_id'], unique=False)
    op.create_table('user_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='日志ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作人ID'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='操作类型(create/update/delete)'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码哈希'),
    sa.Column('role', sa.SMALLINT(), nullable=True, comment='角色(保留字段)'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('is_active', sa.SMALLINT(), nullable=True, comment='是否启用(0-正常 1-封禁 2-注销)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='操作时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_log_created_at'), 'user_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_log_operator_id'), 'user_log', ['operator_id'], unique=False)
    op.create_index(op.f('ix_user_log_user_id'), 'user_log', ['user_id'], unique=False)
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='仪器ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='仪器名称'),
    sa.Column('model', sa.String(length=100), nullable=False, comment='仪器型号'),
    sa.Column('manufacturer', sa.String(length=255), nullable=False, comment='厂商'),
    sa.Column('supplier', sa.String(length=255), nullable=False, comment='供应商'),
    sa.Column('purchase_date', sa.DateTime(), nullable=True, comment='采购时间'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='购入价格'),
    sa.Column('status', sa.SmallInteger(), server_default='0', nullable=False, comment='状态，0-正常 1-维修 2-停用'),
    sa.Column('lab_id', sa.Integer(), nullable=False, comment='所属实验室'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_lab_id'), 'instrument', ['lab_id'], unique=False)
    op.create_table('lab_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='日志ID'),
    sa.Column('lab_id', sa.Integer(), nullable=False, comment='实验室ID'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作人ID'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='操作类型(create/update/delete)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='名称'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='地址'),
    sa.Column('capacity', sa.Integer(), nullable=False, comment='容纳人数'),
    sa.Column('status', sa.SMALLINT(), nullable=False, comment='状态(0-正常 1-维护 2-停用)'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='标签'),
    sa.Column('keyword', sa.String(length=255), nullable=False, comment='关键词'),
    sa.Column('description', sa.TEXT(), nullable=False, comment='实验室说明'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='操作时间'),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_log_created_at'), 'lab_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_lab_log_lab_id'), 'lab_log', ['lab_id'], unique=False)
    op.create_index(op.f('ix_lab_log_operator_id'), 'lab_log', ['operator_id'], unique=False)
    op.create_index(op.f('ix_lab_log_tag_id'), 'lab_log', ['tag_id'], unique=False)
    op.create_table('lab_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('lab_id', sa.Integer(), nullable=False, comment='实验室ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('is_active', sa.SmallInteger(), server_default='0', nullable=False, comment='是否有效(0-有效 1-无效)'),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id', 'user_id', name='lab_user_unique')
    )
    op.create_table('lab_user_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='日志ID'),
    sa.Column('lab_user_id', sa.Integer(), nullable=False, comment='被操作记录ID'),
    sa.Column('lab_id', sa.Integer(), nullable=False, comment='实验室ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作人ID'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='操作类型(create/update/delete)'),
    sa.Column('is_active', sa.SMALLINT(), nullable=True, comment='是否有效(0-正常 1-无效)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='操作时间'),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_user_log_created_at'), 'lab_user_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_lab_user_log_lab_id'), 'lab_user_log', ['lab_id'], unique=False)
    op.create_index(op.f('ix_lab_user_log_lab_user_id'), 'lab_user_log', ['lab_user_id'], unique=False)
    op.create_index(op.f('ix_lab_user_log_operator_id'), 'lab_user_log', ['operator_id'], unique=False)
    op.create_index(op.f('ix_lab_user_log_user_id'), 'lab_user_log', ['user_id'], unique=False)
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='预约ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='申请人ID'),
    sa.Column('lab_id', sa.Integer(), nullable=False, comment='实验室ID'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='结束时间'),
    sa.Column('purpose', sa.TEXT(), nullable=True, comment='使用目的'),
    sa.Column('status', sa.SMALLINT(), server_default='0', nullable=False, comment='状态(0-审批中 1-通过 2-拒绝 3-已取消)'),
    sa.Column('current_level', sa.SMALLINT(), server_default='1', nullable=False, comment='审核阶段(数字为正在审批的层级，0-保存且未提交申请 3-通过所有审批)'),
    sa.Column('is_deleted', sa.SMALLINT(), server_default='0', nullable=False, comment='软删除标记(0-正常 1-已删除)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_lab_id'), 'reservation', ['lab_id'], unique=False)
    op.create_index(op.f('ix_reservation_user_id'), 'reservation', ['user_id'], unique=False)
    op.create_table('approval',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('reservation_id', sa.Integer(), nullable=False, comment='预约ID'),
    sa.Column('approver_id', sa.Integer(), nullable=False, comment='审批人ID'),
    sa.Column('level', sa.SMALLINT(), nullable=False, comment='审批等级(1/2)'),
    sa.Column('status', sa.SMALLINT(), server_default='0', nullable=False, comment='状态(0-通过 1-拒绝)'),
    sa.Column('comment', sa.TEXT(), nullable=False, comment='审批意见'),
    sa.Column('approved_at', sa.DateTime(), nullable=False, comment='审批时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_approver_id'), 'approval', ['approver_id'], unique=False)
    op.create_index(op.f('ix_approval_reservation_id'), 'approval', ['reservation_id'], unique=False)
    op.create_table('instrument_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('instrument_id', sa.Integer(), nullable=False, comment='仪器ID'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作人ID'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='操作类型(create/update/delete)'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='仪器名称'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('manufacturer', sa.String(length=255), nullable=True, comment='厂商'),
    sa.Column('supplier', sa.String(length=255), nullable=True, comment='提供商名称'),
    sa.Column('purchase_date', sa.DateTime(), nullable=True, comment='采购日期'),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='仪器价格'),
    sa.Column('status', sa.SMALLINT(), nullable=False, comment='状态(0-正常 1-维护 2-停用)'),
    sa.Column('lab_id', sa.Integer(), nullable=False, comment='所属实验室'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='操作时间'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_log_created_at'), 'instrument_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_instrument_log_instrument_id'), 'instrument_log', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_instrument_log_operator_id'), 'instrument_log', ['operator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instrument_log_operator_id'), table_name='instrument_log')
    op.drop_index(op.f('ix_instrument_log_instrument_id'), table_name='instrument_log')
    op.drop_index(op.f('ix_instrument_log_created_at'), table_name='instrument_log')
    op.drop_table('instrument_log')
    op.drop_index(op.f('ix_approval_reservation_id'), table_name='approval')
    op.drop_index(op.f('ix_approval_approver_id'), table_name='approval')
    op.drop_table('approval')
    op.drop_index(op.f('ix_reservation_user_id'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_lab_id'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_lab_user_log_user_id'), table_name='lab_user_log')
    op.drop_index(op.f('ix_lab_user_log_operator_id'), table_name='lab_user_log')
    op.drop_index(op.f('ix_lab_user_log_lab_user_id'), table_name='lab_user_log')
    op.drop_index(op.f('ix_lab_user_log_lab_id'), table_name='lab_user_log')
    op.drop_index(op.f('ix_lab_user_log_created_at'), table_name='lab_user_log')
    op.drop_table('lab_user_log')
    op.drop_table('lab_user')
    op.drop_index(op.f('ix_lab_log_tag_id'), table_name='lab_log')
    op.drop_index(op.f('ix_lab_log_operator_id'), table_name='lab_log')
    op.drop_index(op.f('ix_lab_log_lab_id'), table_name='lab_log')
    op.drop_index(op.f('ix_lab_log_created_at'), table_name='lab_log')
    op.drop_table('lab_log')
    op.drop_index(op.f('ix_instrument_lab_id'), table_name='instrument')
    op.drop_table('instrument')
    op.drop_index(op.f('ix_user_log_user_id'), table_name='user_log')
    op.drop_index(op.f('ix_user_log_operator_id'), table_name='user_log')
    op.drop_index(op.f('ix_user_log_created_at'), table_name='user_log')
    op.drop_table('user_log')
    op.drop_index(op.f('ix_tag_user_log_user_id'), table_name='tag_user_log')
    op.drop_index(op.f('ix_tag_user_log_tag_user_id'), table_name='tag_user_log')
    op.drop_index(op.f('ix_tag_user_log_tag_id'), table_name='tag_user_log')
    op.drop_index(op.f('ix_tag_user_log_operator_id'), table_name='tag_user_log')
    op.drop_index(op.f('ix_tag_user_log_created_at'), table_name='tag_user_log')
    op.drop_table('tag_user_log')
    op.drop_table('tag_user')
    op.drop_index(op.f('ix_tag_log_tag_id'), table_name='tag_log')
    op.drop_index(op.f('ix_tag_log_operator_id'), table_name='tag_log')
    op.drop_index(op.f('ix_tag_log_created_at'), table_name='tag_log')
    op.drop_table('tag_log')
    op.drop_index(op.f('ix_lab_tag_id'), table_name='lab')
    op.drop_table('lab')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('tag')
    # ### end Alembic commands ###
