// -*- coding: utf-8 -*-
// File: mockData.js
// Created: 2026-03-30
// Author: zhuimeng
// Description: Mock 数据用于预览

export const MOCK_USER = {
  id: 1,
  username: 'admin',
  name: '管理员',
  email: 'admin@labflow.com',
  role: 0,
};

export const MOCK_LABS = [
  {
    id: 1,
    name: '化学实验室 A',
    address: 'A 楼 302',
    capacity: 20,
    status: 0,
    manager: '张教授',
    phone: '010-12345678',
    description: '主要用于化学实验教学和科研',
  },
  {
    id: 2,
    name: '生物实验室 B',
    address: 'B 楼 210',
    capacity: 15,
    status: 0,
    manager: '李研究员',
    phone: '010-87654321',
    description: '生物化学分析实验室',
  },
  {
    id: 3,
    name: '物理实验室 C',
    address: 'C 楼 401',
    capacity: 25,
    status: 1,
    manager: '王博士',
    phone: '010-66668888',
    description: '物理基础实验室',
  },
  {
    id: 4,
    name: '材料实验室 D',
    address: 'D 楼 105',
    capacity: 18,
    status: 0,
    manager: '赵工程师',
    phone: '010-99998888',
    description: '材料科学与工程实验室',
  },
];

export const MOCK_INSTRUMENTS = [
  {
    id: 1,
    name: '高效液相色谱仪',
    model: 'Agilent 1260 Infinity II',
    manufacturer: 'Agilent Technologies',
    supplier: '安捷伦科技有限公司',
    purchase_date: '2024-06-15',
    price: 450000,
    status: 0,
    lab_id: 1,
    lab: { id: 1, name: '化学实验室 A' },
    remark: '主要用途：化合物分离与定量分析',
    created_at: '2024-06-15T08:00:00Z',
  },
  {
    id: 2,
    name: '全自动核酸提取仪',
    model: 'QIAcube Connect',
    manufacturer: 'QIAGEN',
    supplier: '凯杰企业管理（上海）有限公司',
    purchase_date: '2024-03-20',
    price: 280000,
    status: 0,
    lab_id: 2,
    lab: { id: 2, name: '生物实验室 B' },
    remark: '用于 DNA/RNA 提取',
    created_at: '2024-03-20T10:30:00Z',
  },
  {
    id: 3,
    name: '傅里叶红外光谱仪',
    model: 'Nicolet iS50',
    manufacturer: 'Thermo Fisher Scientific',
    supplier: '赛默飞世尔科技（中国）有限公司',
    purchase_date: '2023-11-08',
    price: 320000,
    status: 1,
    lab_id: 3,
    lab: { id: 3, name: '物理实验室 C' },
    remark: '维修中，预计下周恢复',
    created_at: '2023-11-08T14:20:00Z',
  },
  {
    id: 4,
    name: '扫描电子显微镜',
    model: 'JSM-7900F',
    manufacturer: 'JEOL',
    supplier: '日本电子株式会社',
    purchase_date: '2023-05-12',
    price: 1200000,
    status: 0,
    lab_id: 4,
    lab: { id: 4, name: '材料实验室 D' },
    remark: '高精度材料表征设备',
    created_at: '2023-05-12T09:00:00Z',
  },
  {
    id: 5,
    name: '实时荧光定量 PCR 仪',
    model: 'QuantStudio 7 Pro',
    manufacturer: 'Applied Biosystems',
    supplier: '赛默飞世尔科技（中国）有限公司',
    purchase_date: '2024-01-10',
    price: 380000,
    status: 0,
    lab_id: 2,
    lab: { id: 2, name: '生物实验室 B' },
    remark: '用于基因表达分析',
    created_at: '2024-01-10T11:15:00Z',
  },
  {
    id: 6,
    name: '超低温冷冻离心机',
    model: 'CP100NX',
    manufacturer: 'Hitachi Koki',
    supplier: '日立（中国）有限公司',
    purchase_date: '2023-08-25',
    price: 180000,
    status: 2,
    lab_id: 1,
    lab: { id: 1, name: '化学实验室 A' },
    remark: '已停用，待报废处理',
    created_at: '2023-08-25T16:45:00Z',
  },
];

export const MOCK_RESERVATIONS = [
  {
    id: 1,
    user_id: 2,
    user_name: '张三',
    instrument_id: 1,
    instrument_name: '高效液相色谱仪',
    start_time: '2026-03-30T09:00:00Z',
    end_time: '2026-03-30T12:00:00Z',
    status: 0,
    current_level: 1,
    purpose: '样品成分分析',
    created_at: '2026-03-28T10:00:00Z',
  },
  {
    id: 2,
    user_id: 3,
    user_name: '李四',
    instrument_id: 2,
    instrument_name: '全自动核酸提取仪',
    start_time: '2026-03-31T14:00:00Z',
    end_time: '2026-03-31T17:00:00Z',
    status: 1,
    current_level: 3,
    purpose: 'DNA 提取实验',
    created_at: '2026-03-27T15:30:00Z',
  },
  {
    id: 3,
    user_id: 4,
    user_name: '王五',
    instrument_id: 4,
    instrument_name: '扫描电子显微镜',
    start_time: '2026-04-01T09:00:00Z',
    end_time: '2026-04-01T16:00:00Z',
    status: 0,
    current_level: 1,
    purpose: '材料形貌表征',
    created_at: '2026-03-29T09:00:00Z',
  },
];

export const MOCK_OVERVIEW = {
  deviceTotal: 6,
  labTechnicians: 24,
  currentProjects: 8,
};

export const MOCK_DEVICE_STATUS = {
  available: 3,
  reserved: 1,
  maintenance: 1,
  fault: 1,
};

export const MOCK_RECENT_ACTIVITIES = [
  {
    id: '1',
    user: '李四',
    action: '提交了实验报告',
    timestamp: '今天 14:00',
    type: 'report',
  },
  {
    id: '2',
    user: '张三',
    action: '预约了高效液相色谱仪',
    deviceName: '高效液相色谱仪',
    timestamp: '昨天 16:30',
    type: 'reservation',
  },
  {
    id: '3',
    user: '系统',
    action: '新设备已到货',
    deviceName: '高效液相色谱仪',
    timestamp: '昨天 10:15',
    type: 'device',
  },
  {
    id: '4',
    user: '王五',
    action: '完成离心机维护',
    deviceName: '离心机',
    timestamp: '前天 09:45',
    type: 'maintenance',
  },
];
